[package]
name = "voronoi_simd"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.30.0", features = ["persistence"] }
egui_extras = "0.30.0"
fnv = "1.0.7"
glam = { version = "0.29.2", features = ["rand"] }
rand = "0.8.5"
rustc-hash = "2.1.0"
